# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Getting Started
  version:
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: Overview
      url: /prod_overview.html
      output: web
    - title: Versioning and Backward Compatibility
      url: /prod_versioning.html
      output: web
    - title: Support
      url: /prod_support.html
      output: web
