# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Overview
  version:
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Overview
    output: web, pdf
    folderitems:
    - title: Overview
      url: /prod_overview.html
      output: web

    - title: General API Rules
      url: /prod_generalrules.html
      output: web

    - title: Versioning and Backward Compatibility
      url: /prod_versioning.html
      output: web

    - title: Support
      url: /prod_support.html
      output: web

  - title: Integration Models
    output: web, pdf
    folderitems:
    - title: Integration Overview
      url: /prod_integrationoverview.html
      output: web

    - title: Merchant Integration
      url: /prod_merchantintegration.html
      output: web

    - title: Partner Integration
      url: /prod_partnerintegration.html
      output: web

  - title: Nuapay Console
    output: web, pdf
    folderitems:
    - title: Overview
      url: /prod_consoleoverview.html
      output: web

    - title: API Key Configuration
      url: /prod_consoleapi.html
      output: web

    - title: Webhook Configuration
      url: /prod_consolewebhooks.html
      output: web

    - title: PKI Management
      url: /prod_consolewpkimgmt.html
      output: web

    - title: Merchant Management
      url: /prod_consolemrchmgmt.html
      output: web
