version: '2'
services:
  server:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      dockerfile: Dockerfile
    image: result/latest
    command: jekyll serve --watch --drafts --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ".:/src"